# Generated by Django 5.2.11 on 2026-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='balance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
